language: python
before_install:
    - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p /home/travis/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes --quiet conda
install:
    - conda create -n testenv --yes pip python=2.7
    - source activate testenv
    - conda install --yes --quiet numpy scipy matplotlib numba pandas scikit-learn nose coverage mock
    - pip install -q flake8
    - pip install coverage coveralls
    - pip install -e ./
script:
    - nosetests tests/ --with-coverage
    - flake8 --count spykes
after_success:
    - coveralls
